### ISSUE TITLE
New functional testing system

### ISSUE THREAD

**Issue by kochetkov** [LibProtection/libprotection-dotnet#34]
1. Implement additional public method in SafeString class: `FormatResult FormatEx(string format, params object[] args)`. Where FormatResult is:
```csharp
public class FormatResult
{
    // array of tokenization artifacts
    public Token[] Tokens;
    // true if an attack was detected during formatting
    public bool IsAttackDetected;
    // if  IsAttackDetected == true, contains an index of attacked args element 
    public int InjectionPointIndex;
    // result of Formatting (should be null if IsAttackDetected == true)
    public FormattedString;
}
```

2. Refactor current functional test system to replace plain-text representation of test cases to the JSON one. Following class should be used for test-case representation:
```csharp
[Serializable]
public class TestCase
{
    // name of test case (should be used for NUnit's `TestCaseData(...).SetName`)
    public string Name;
    // name of language provider
    public string LanguageProvider;
    // format string template
    public string Format;
    // format string arguments
    public string[] Arguments;
    // expected format result (should be null for new test cases)
    public FormatResult Result;
}
```
Each test case should be represented as TestCase's instance serialized to JSON file at libprotection-common repository. If FormatResult is null, test runner should show assert (as current one), generate FormatResult and serialize the resultant TestCase's instance to the runner's working directory.

**Comment by frenzyigor** [comment]
feature added
