### ISSUE TITLE
Use common TextSpan representation

### ISSUE THREAD

**Issue by KvanTTT** [LibProtection/libprotection-dotnet#39]
Both [Roslyn](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Text/TextSpan.cs) and [PT.PM](https://github.com/PositiveTechnologies/PT.PM/blob/dev/Sources/PT.PM.Common/TextSpan.cs) use the following format of text spans with inclusive start and exclusive end bounds: `[start..end)`. 

But libprotection uses [Ranges](https://github.com/LibProtection/libprotection-dotnet/blob/dev/sources/LibProtection.Injections/LibProtection.Injections/Range.cs) with the inclusive end bound: `[start..end]`. You are unable to denote zero-width spans with such format, but with Roslyn spans you can.

I suggest using more standardized text spans style. Also, for zero-width spans shortened syntax can be used: `[pos)`.

Moreover, if you want to use line-column text spans (more convenient for reading) you can use the following format: `[start-line,start-column..end-line,end-column)`.  See [LineColumnTextSpan](https://github.com/PositiveTechnologies/PT.PM/blob/dev/Sources/PT.PM.Common/LineColumnTextSpan.cs) for detail.

I guess this issue related to all libprotection projects (dotnet, java, cpp, etc.).

**Comment by kochetkov** [comment]
Thanks! Actually, it's even a bug, because the library can not currently process format strings with empty arguments correctly.
