### ISSUE TITLE
upperBound variable should be created inside if (!currentFragment.IsSafe) {...} scope.

### ISSUE THREAD

**Issue by pollnossa** [LibProtection/libprotection-dotnet#42]
https://github.com/LibProtection/libprotection-dotnet/blob/7933c292a3f5801b729039cca0c6ff9f69706703/sources/LibProtection.Injections/LibProtection.Injections/Formatting/Formatter.cs#L65

**Comment by kochetkov** [comment]
@frenzyigor ?
